name: CI

on:
  push:
    branches: [main]
    # Release tag format is [module-name]-v[androidx-version]-[ktx-version]
    # For example: fragment-ktx-v1.3.5-0
    tags: ['*-ktx-v*-[0-9]+']
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Check
        run: ./gradlew check -xlint

      - name: Run Detekt
        run: ./gradlew detektAll detektReleaseAll

  publish:
    name: Publish KTX
    needs: check
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Get module name from tag
        id: get-module-name
        run: |
          tag=${GITHUB_REF#refs/tags/}
          echo "result=${tag/-v*}" >> "$GITHUB_OUTPUT"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Publish
        run: ./gradlew :ktx:${{ steps.get-module-name.outputs.result }}:publish
        env:
          ORG_GRADLE_PROJECT_githubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
